{{- if .Values.pgadmin.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
spec:
  ingressClassName: {{ .Values.pgadmin.ingress.ingressClassName }}
  rules:
    {{- range .Values.pgadmin.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: pgadmin
                port:
                  number: {{ $.Values.pgadmin.port }}
          {{- end }}
    {{- end }}
{{- end }}